<?php

/**
 * This is the model base class for the table "administrador".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Administrador".
 *
 * Columns in table "administrador" available as properties of the model,
 * followed by relations of table "administrador" available as properties of the model.
 *
 * @property integer $id_user
 *
 * @property Usuario $idUser
 */
abstract class BaseAdministrador extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'administrador';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Administrador|Administradores', $n);
	}

	public static function representingColumn() {
		return 'id_user';
	}

	public function rules() {
		return array(
			//array('id_user', 'required'),
			array('id_user', 'numerical', 'integerOnly'=>true),
			array('id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUser' => array(self::BELONGS_TO, 'Usuario', 'id_user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_user' => null,
			'idUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}