<?php

/**
 * This is the model base class for the table "paquete".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Paquete".
 *
 * Columns in table "paquete" available as properties of the model,
 * followed by relations of table "paquete" available as properties of the model.
 *
 * @property integer $cod_paquete
 * @property double $peso
 * @property integer $cod_producto
 * @property integer $cod_presupuesto
 * @property double $alto
 * @property double $ancho
 * @property string $descripcion
 * @property integer $cod_encargo
 *
 * @property Producto $codProducto
 * @property Presupuesto $codPresupuesto
 * @property Encargo $codEncargo
 */
abstract class BasePaquete extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'paquete';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Paquete|Paquetes', $n);
	}

	public static function representingColumn() {
		return array(': ','codProducto','descripcion');
	}

	public function rules() {
		return array(
			array('peso, cod_producto, alto, ancho', 'required'),
			array('cod_producto, cod_presupuesto, cod_encargo', 'numerical', 'integerOnly'=>true),
			array('peso, alto, ancho', 'numerical'),
			array('descripcion', 'length', 'max'=>250),
			array('descripcion, cod_encargo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('cod_paquete, peso, cod_producto, cod_presupuesto, alto, ancho, descripcion, cod_encargo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'codProducto' => array(self::BELONGS_TO, 'Producto', 'cod_producto'),
			'codPresupuesto' => array(self::BELONGS_TO, 'Presupuesto', 'cod_presupuesto'),
			'codEncargo' => array(self::BELONGS_TO, 'Encargo', 'cod_encargo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cod_paquete' => Yii::t('app', 'Cod Paquete'),
			'peso' => Yii::t('app', 'Peso'),
			'cod_producto' => null,
			'cod_presupuesto' => null,
			'alto' => Yii::t('app', 'Alto'),
			'ancho' => Yii::t('app', 'Ancho'),
			'descripcion' => Yii::t('app', 'Descripcion del paquete'),
			'cod_encargo' => null,
			'codProducto' => null,
			'codPresupuesto' => null,
			'codEncargo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
                
                $conexion = $conexion = Util::connect();
                if(Util::isEmpresa(Yii::app()->user->name))
                {
                    
                }
                mysql_close($conexion);
		$criteria->compare('cod_paquete', $this->cod_paquete);
		$criteria->compare('peso', $this->peso);
		$criteria->compare('cod_producto', $this->cod_producto);
		$criteria->compare('cod_presupuesto', $this->cod_presupuesto);
		$criteria->compare('alto', $this->alto);
		$criteria->compare('ancho', $this->ancho);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('cod_encargo', $this->cod_encargo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        public function searchb($id) {//id encargo
		$criteria = new CDbCriteria;
                $id=$id-1;
                $conexion = $conexion = Util::connect();
                $query="SELECT `cod_envio` FROM `encargo` WHERE `cod_encargo` = ".$id;
                $r=mysql_query($query,$conexion) or die (mysql_error());
                $idenvio=mysql_fetch_array($r);
                $idenvio=$idenvio["cod_envio"];
                
                $ids=-1;
                if($idenvio!==null)
                {
                    $query="SELECT `cod_presupuesto` FROM `envio` WHERE `cod_envio` = ".$idenvio;
                    $r=mysql_query($query,$conexion) or die (mysql_error());
                    $ids=mysql_fetch_array($r);
                    $ids=$ids["cod_presupuesto"];
                }
                
                
                mysql_close($conexion);
		$criteria->compare('cod_paquete', $this->cod_paquete);
		$criteria->compare('peso', $this->peso);
		$criteria->compare('cod_producto', $this->cod_producto);
		$criteria->compare('cod_presupuesto', $ids,true);
		$criteria->compare('alto', $this->alto);
		$criteria->compare('ancho', $this->ancho);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('cod_encargo', $this->cod_encargo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}