<?php

/**
 * This is the model base class for the table "datos_personales".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Datos_personales".
 *
 * Columns in table "datos_personales" available as properties of the model,
 * followed by relations of table "datos_personales" available as properties of the model.
 *
 * @property string $nombre
 * @property string $apellido
 * @property string $cedula
 * @property string $correo
 * @property string $RIF
 * @property string $numero_telefono
 * @property integer $id_user
 *
 * @property Usuario $idUser
 */
abstract class BaseDatos_personales extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'datos_personales';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Datos personales|Datos personales', $n);
	}

	public static function representingColumn() {
		return array('nombre','apellido');
	}

	public function rules() {
		return array(
			array('id_user', 'required'),
			array('id_user', 'numerical', 'integerOnly'=>true),
			array('nombre, apellido', 'length', 'max'=>25),
			array('cedula, numero_telefono', 'length', 'max'=>10),
			array('correo', 'length', 'max'=>50),
			array('RIF', 'length', 'max'=>20),
			array('nombre, apellido, cedula, correo, RIF, numero_telefono', 'default', 'setOnEmpty' => true, 'value' => null),
			array('nombre, apellido, cedula, correo, RIF, numero_telefono, id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUser' => array(self::BELONGS_TO, 'Usuario', 'id_user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'nombre' => Yii::t('app', 'Nombre'),
			'apellido' => Yii::t('app', 'Apellido'),
			'cedula' => Yii::t('app', 'Cedula'),
			'correo' => Yii::t('app', 'Correo'),
			'RIF' => Yii::t('app', 'Rif'),
			'numero_telefono' => Yii::t('app', 'Numero Telefono'),
			'id_user' => null,
			'idUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellido', $this->apellido, true);
		$criteria->compare('cedula', $this->cedula, true);
		$criteria->compare('correo', $this->correo, true);
		$criteria->compare('RIF', $this->RIF, true);
		$criteria->compare('numero_telefono', $this->numero_telefono, true);
		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}