<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $id_user
 * @property string $clave
 * @property string $nombre_usuario
 * @property string $fecha_de_registro
 *
 * @property Administrador $administrador
 * @property Chofer $chofer
 * @property DatosPersonales $datosPersonales
 * @property Empresa $empresa
 * @property Operador $operador
 */
abstract class BaseUsuario extends GxActiveRecord {
    public $repeatpassword;
    public $actualpass;
    public $newpass;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'nombre_usuario';
	}

	public function rules() {
		return array(
			array('clave, nombre_usuario', 'required','on'=>'create'),
			array('clave, nombre_usuario, fecha_de_registro', 'length', 'max'=>25),
                        array('actualpass, newpass','length', 'max'=>25),
                        array('repeatpassword', 'compare', 'compareAttribute'=>'clave', 'message'=>"Las contraseñas no coinciden",'on'=>'create'),
                        array('actualpass', 'compare', 'allowEmpty'=>true, 'compareAttribute'=>'clave', 'message'=>"La contraseña no coincide con la anterior",'on'=>'update'),
                        array('repeatpassword', 'compare', 'compareAttribute'=>'newpass', 'message'=>"Las nuevas contraseñas no coinciden",'on'=>'update'),
				
                        array('id_user, clave, nombre_usuario, fecha_de_registro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'administrador' => array(self::HAS_ONE, 'Administrador', 'id_user'),
			'chofer' => array(self::HAS_ONE, 'Chofer', 'id_user'),
			'datosPersonales' => array(self::HAS_ONE, 'DatosPersonales', 'id_user'),
			'empresa' => array(self::HAS_ONE, 'Empresa', 'id_user'),
			'operador' => array(self::HAS_ONE, 'Operador', 'id_user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_user' => Yii::t('app', 'Id de Usuario'),
			'clave' => Yii::t('app', 'Contraseña'),
			'nombre_usuario' => Yii::t('app', 'Nombre De Usuario'),
			'fecha_de_registro' => Yii::t('app', 'Fecha De Registro'),
			'administrador' => null,
			'chofer' => null,
			'datosPersonales' => null,
			'empresa' => null,
			'operador' => null,
                        'repeatpassword' =>Yii::t('app','Repita la Contraseña'),
                        'actualpass'=>Yii::t('app','Contraseña actual'),
                        'newpass'=>Yii::t('app','Nueva Contrañse'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_user', $this->id_user);
		$criteria->compare('clave', $this->clave, true);
		$criteria->compare('nombre_usuario', $this->nombre_usuario, true);
		$criteria->compare('fecha_de_registro', $this->fecha_de_registro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}