<?php

/**
 * This is the model base class for the table "camion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Camion".
 *
 * Columns in table "camion" available as properties of the model,
 * followed by relations of table "camion" available as properties of the model.
 *
 * @property string $placa
 * @property integer $distancia_optima
 * @property double $peso_max
 * @property double $alto
 * @property integer $mantenimiento
 * @property integer $fragil
 * @property integer $refrigerado
 * @property integer $vivo
 * @property integer $peligroso
 * @property integer $id_chofer
 * @property double $ancho
 *
 * @property Chofer $idChofer
 * @property Encargo[] $encargos
 * @property Paquete[] $paquetes
 */
abstract class BaseCamion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'camion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Camion|Camiones', $n);
	}

	public static function representingColumn() {
		return 'placa';
	}

	public function rules() {
		return array(
			array('placa, peso_max, alto, mantenimiento, fragil, refrigerado, vivo, peligroso, ancho', 'required'),
			array('distancia_optima, mantenimiento, fragil, refrigerado, vivo, peligroso, id_chofer', 'numerical', 'integerOnly'=>true),
			array('peso_max, alto, ancho', 'numerical'),
			array('placa', 'length', 'max'=>10),
			array('distancia_optima, id_chofer, ancho', 'default', 'setOnEmpty' => true, 'value' => null),
			array('placa, distancia_optima, peso_max, alto, mantenimiento, fragil, refrigerado, vivo, peligroso, id_chofer, ancho', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idChofer' => array(self::BELONGS_TO, 'Chofer', 'id_chofer'),
			'encargos' => array(self::HAS_MANY, 'Encargo', 'placa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'placa' => Yii::t('app', 'Placa Del Vehiculo'),
			'distancia_optima' => Yii::t('app', 'Distancia Optima Sugerida'),
			'peso_max' => Yii::t('app', 'Peso Maximo Soportado'),
			'alto' => Yii::t('app', 'Alto'),
			'mantenimiento' => Yii::t('app', 'Mantenimiento'),
			'fragil' => Yii::t('app', 'Fragil'),
			'refrigerado' => Yii::t('app', 'Refrigerado'),
			'vivo' => Yii::t('app', 'Vivo'),
			'peligroso' => Yii::t('app', 'Peligroso'),
			'id_chofer' => null,
			'ancho' => Yii::t('app', 'Ancho'),
			'idChofer' => null,
			'encargos' => null,
			'paquetes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('placa', $this->placa, true);
		$criteria->compare('distancia_optima', $this->distancia_optima);
		$criteria->compare('peso_max', $this->peso_max);
		$criteria->compare('alto', $this->alto);
		$criteria->compare('mantenimiento', $this->mantenimiento);
		$criteria->compare('fragil', $this->fragil);
		$criteria->compare('refrigerado', $this->refrigerado);
		$criteria->compare('vivo', $this->vivo);
		$criteria->compare('peligroso', $this->peligroso);
		$criteria->compare('id_chofer', $this->id_chofer);
		$criteria->compare('ancho', $this->ancho);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}