<?php

/**
 * This is the model base class for the table "empresa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresa".
 *
 * Columns in table "empresa" available as properties of the model,
 * followed by relations of table "empresa" available as properties of the model.
 *
 * @property integer $id_user
 *
 * @property Usuario $idUser
 * @property Presupuesto[] $presupuestos
 * @property Producto[] $productos
 */
abstract class BaseEmpresa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empresa|Empresas', $n);
	}

	public static function representingColumn() {
		return 'id_user';
	}

	public function rules() {
		return array(
			array('id_user', 'required'),
			array('id_user', 'numerical', 'integerOnly'=>true),
			array('id_user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUser' => array(self::BELONGS_TO, 'Usuario', 'id_user'),
			'presupuestos' => array(self::HAS_MANY, 'Presupuesto', 'id_empresa'),
			'productos' => array(self::HAS_MANY, 'Producto', 'Id_empresa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_user' => null,
			'idUser' => null,
			'presupuestos' => null,
			'productos' => Yii::t('app', 'Productos asociados'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_user', $this->id_user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}